### ISSUE TITLE
Inject GPS doesn't allow BAUD rate choice for UDP Host

### ISSUE THREAD

**Issue by Jman841** [diydrones/MissionPlanner#978]
When I try to inject GPS for the Piksi RTK GPS's the latest version of mission planner has the BAUD rate for UDP Host blanked out and doesnt allow it to be selected or automatically select it. The only way to get it to work is to go to a COM port, choose the BAUD rate, then go back to UDP Host and it will be saved.

**Comment by meee1** [comment]
the udp option does not use the baud rate. there was a bug in older versions that needed it set to something non 0, but that is fixed.

**Comment by Jman841** [comment]
That is strange, if I click "Connect" with UDP Host selected and the baud rate blank it gives me an error that says "Invalid BaudRate" and does not let me continue. The only way to get it to work currently is to go to a COM port, choose a baud rate, then back to UDP Host.

**Comment by meee1** [comment]
yes that was the bug I was talking about, the latest beta fix's that.

**Comment by Jman841** [comment]
AH ok, I'll close this then.

**Comment by Jman841** [comment]
Just tested again today with Beta 1.31.3 and it is still an issue. You still have to go to a COM port to choose the BAUD rate for UDP Host or else it says invalid baud rate.

**Comment by meee1** [comment]
i discovered i only half fixed this.

**Comment by meee1** [comment]
final fix is here
https://github.com/diydrones/MissionPlanner/commit/e51663df75c189a98bd1ad2b31a3f085190e208a
